// Generated by gencpp from file object_avoid/Object.msg
// DO NOT EDIT!


#ifndef OBJECT_AVOID_MESSAGE_OBJECT_H
#define OBJECT_AVOID_MESSAGE_OBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace object_avoid
{
template <class ContainerAllocator>
struct Object_
{
  typedef Object_<ContainerAllocator> Type;

  Object_()
    : front(0)
    , left(0)
    , right(0)
    , left2(0)
    , right2(0)  {
    }
  Object_(const ContainerAllocator& _alloc)
    : front(0)
    , left(0)
    , right(0)
    , left2(0)
    , right2(0)  {
  (void)_alloc;
    }



   typedef int32_t _front_type;
  _front_type front;

   typedef int32_t _left_type;
  _left_type left;

   typedef int32_t _right_type;
  _right_type right;

   typedef int32_t _left2_type;
  _left2_type left2;

   typedef int32_t _right2_type;
  _right2_type right2;





  typedef boost::shared_ptr< ::object_avoid::Object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::object_avoid::Object_<ContainerAllocator> const> ConstPtr;

}; // struct Object_

typedef ::object_avoid::Object_<std::allocator<void> > Object;

typedef boost::shared_ptr< ::object_avoid::Object > ObjectPtr;
typedef boost::shared_ptr< ::object_avoid::Object const> ObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::object_avoid::Object_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::object_avoid::Object_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::object_avoid::Object_<ContainerAllocator1> & lhs, const ::object_avoid::Object_<ContainerAllocator2> & rhs)
{
  return lhs.front == rhs.front &&
    lhs.left == rhs.left &&
    lhs.right == rhs.right &&
    lhs.left2 == rhs.left2 &&
    lhs.right2 == rhs.right2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::object_avoid::Object_<ContainerAllocator1> & lhs, const ::object_avoid::Object_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace object_avoid

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::object_avoid::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::object_avoid::Object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_avoid::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::object_avoid::Object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_avoid::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::object_avoid::Object_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::object_avoid::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0581ce5ecc11cefc11e361045e60699";
  }

  static const char* value(const ::object_avoid::Object_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0581ce5ecc11cefULL;
  static const uint64_t static_value2 = 0xc11e361045e60699ULL;
};

template<class ContainerAllocator>
struct DataType< ::object_avoid::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "object_avoid/Object";
  }

  static const char* value(const ::object_avoid::Object_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::object_avoid::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 front\n"
"int32 left\n"
"int32 right\n"
"int32 left2\n"
"int32 right2\n"
;
  }

  static const char* value(const ::object_avoid::Object_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::object_avoid::Object_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.front);
      stream.next(m.left);
      stream.next(m.right);
      stream.next(m.left2);
      stream.next(m.right2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Object_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::object_avoid::Object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::object_avoid::Object_<ContainerAllocator>& v)
  {
    s << indent << "front: ";
    Printer<int32_t>::stream(s, indent + "  ", v.front);
    s << indent << "left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right);
    s << indent << "left2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.left2);
    s << indent << "right2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.right2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBJECT_AVOID_MESSAGE_OBJECT_H
